# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-04 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=15, verbose_name='\u544a\u8b66\u7ea7\u522b')),
                ('item', models.CharField(max_length=50, verbose_name='\u544a\u8b66\u9879')),
                ('value', models.TextField(verbose_name='\u544a\u8b66\u5185\u5bb9')),
                ('ip', models.CharField(max_length=120, verbose_name='ip\u5730\u5740')),
                ('resolve', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u89e3\u51b3')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u62a5\u8b66\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u62a5\u8b66\u4fe1\u606f',
                'verbose_name_plural': '\u62a5\u8b66\u4fe1\u606f',
            },
        ),
    ]
