# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-04 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alarm',
            table='alarm',
        ),
    ]
