# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-20 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0007_asset_kernel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_free', models.IntegerField(verbose_name='mem free')),
                ('mem_buff', models.IntegerField(verbose_name='mem buff')),
                ('mem_cache', models.IntegerField(verbose_name='mem cache')),
                ('io_bi', models.IntegerField(verbose_name='io bi')),
                ('io_bo', models.IntegerField(verbose_name='io bo')),
                ('cpu_use', models.IntegerField(verbose_name='cpu us')),
                ('cpu_sys', models.IntegerField(verbose_name='cpu sy')),
                ('cpu_idle', models.IntegerField(verbose_name='cpu id')),
                ('monitor_time', models.DateTimeField(verbose_name='\u53d6\u503c\u65f6\u95f4')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='\u5173\u8054\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u76d1\u63a7\u4fe1\u606f',
                'verbose_name_plural': '\u76d1\u63a7\u4fe1\u606f',
            },
        ),
    ]
