# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-21 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('duser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('command', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            bases=('auth.group',),
        ),
    ]
