# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-21 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0002_usergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
