# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-21 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0004_auto_20171121_1647'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergroup',
            table='dct_group',
        ),
    ]
