# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-21 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0008_auto_20171121_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': '\u6388\u6743\u7ec4', 'verbose_name_plural': '\u6388\u6743\u7ec4'},
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='dct_group',
        ),
    ]
