# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-22 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0010_auto_20171121_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dctusermanger',
            name='group',
        ),
    ]
