# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0013_dctusermanger_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authgroupmanage',
            name='asset_group_num',
        ),
        migrations.RemoveField(
            model_name='authgroupmanage',
            name='user_num',
        ),
        migrations.AddField(
            model_name='authgroupmanage',
            name='asset_group_list',
            field=models.TextField(default=1, verbose_name='\u4e3b\u673a\u5217\u8868'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authgroupmanage',
            name='user_list',
            field=models.TextField(default=2, verbose_name='\u7528\u6237\u5217\u8868'),
            preserve_default=False,
        ),
    ]
