# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-22 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0014_auto_20171122_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authgroupmanage',
            name='asset_group_list',
            field=models.TextField(blank=True, null=True, verbose_name='\u4e3b\u673a\u5217\u8868'),
        ),
        migrations.AlterField(
            model_name='authgroupmanage',
            name='user_list',
            field=models.TextField(blank=True, null=True, verbose_name='\u7528\u6237\u5217\u8868'),
        ),
    ]
