# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-22 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0015_auto_20171122_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authgroupmanage',
            name='asset_group_list',
        ),
        migrations.RemoveField(
            model_name='authgroupmanage',
            name='user_list',
        ),
    ]
