# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0016_auto_20171122_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='authgroupmanage',
            name='groups',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
