# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-23 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0020_remove_dctusermanger_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authgroupmanage',
            name='groups',
        ),
        migrations.AddField(
            model_name='authgroupmanage',
            name='asset',
            field=models.TextField(blank=True, null=True, verbose_name='\u6388\u6743\u8d44\u4ea7'),
        ),
        migrations.AddField(
            model_name='authgroupmanage',
            name='users',
            field=models.TextField(blank=True, null=True, verbose_name='\u6388\u6743\u7528\u6237'),
        ),
    ]
