# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-08 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4e3b\u673aIP')),
                ('other_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5176\u4ed6IP')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='\u4e3b\u673a\u540d')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='\u7aef\u53e3\u53f7')),
                ('username', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u7ba1\u7406\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5bc6\u7801')),
                ('mac', models.CharField(blank=True, max_length=20, null=True, verbose_name='MAC\u5730\u5740')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u5b58')),
                ('disk', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u786c\u76d8')),
                ('system_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
                ('system_version', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c\u53f7')),
                ('system_arch', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u7cfb\u7edf\u5e73\u53f0')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'dct_assets',
                'verbose_name': '\u4e3b\u673a\u8d44\u4ea7',
                'verbose_name_plural': '\u4e3b\u673a\u8d44\u4ea7',
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7ec4\u540d')),
                ('comment', models.TextField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ManyToManyField(blank=True, to='asset.AssetGroup', verbose_name='\u6240\u5c5e\u4e3b\u673a\u7ec4'),
        ),
    ]
