# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-08 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20171108_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(max_length=128, verbose_name='\u4e3b\u673a\u540d'),
        ),
    ]
