# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-09 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20171109_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='kernel',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u6838'),
        ),
    ]
