# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-21 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_asset_kernel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='\u4e3b\u673aIP'),
        ),
    ]
