# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20171121_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.CharField(default=11, max_length=60, unique=True, verbose_name='\u4e3b\u673aIP'),
            preserve_default=False,
        ),
    ]
