# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20171130_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='\u6587\u4ef6\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='suffix',
            field=models.CharField(default=1, max_length=10, verbose_name='\u540e\u7f00'),
            preserve_default=False,
        ),
    ]
